# syntax=docker/dockerfile:1
FROM hello-world:latest

# Labels
LABEL io.slateci.image.name="banana"
LABEL io.slateci.image.tags=""
LABEL org.opencontainers.image.authors="adam.h.griffith@utah.edu"
LABEL org.opencontainers.image.description="This is a proof-of-concept container for OCI labels."
LABEL org.opencontainers.image.licenses="Unlicense"
LABEL org.opencontainers.image.title="Banana"
LABEL org.opencontainers.image.url="https://github.com/slateci/docker-images"
LABEL org.opencontainers.image.vendor="SLATECI"
LABEL org.opencontainers.image.version="1.0.0"
