name: Force Build and Push Container Images

on:
  workflow_dispatch:
    inputs:
      folders:
        description: 'Comma separated list of folders to force build (or ALL to build all)'
        required: True
        default: 'ALL'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with Github container registry
        run: echo '${{ secrets.GITHUB_TOKEN }}' | docker login https://ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Authenticate with OSG Hub
        run: echo '${{ secrets.OSG_HUB_ACCESS_TOKEN }}' | docker login https://hub.opensciencegrid.org -u '${{ secrets.OSG_HUB_USERNAME }}' --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Install script dependencies
      #   run: pip3 install pyyaml

      - name: Run build.py force-build-all
        run: ./build.py force-build-all
        if: ${{ github.events.inputs.folders == 'ALL' }}

      - name: Run build.py force-build
        run: ./build.py force-build ${{ github.events.inputs.folders }}
        if: ${{ github.events.inputs.folders != 'ALL' }}
