name: Manual - Force Build and Push Container Images

on:
  workflow_dispatch:
    inputs:
      folders:
        description: 'Comma separated list of folders to force build (or ALL to build all)'
        required: True
        default: 'ALL'

      clowntown:
        description: 'This is a potentially destructive operation (see README). Type "CONFIRM" to acknowledge the risks.'
        required: True

concurrency: push_to_stable

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/stable' && github.event.inputs.clowntown == 'CONFIRM' }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Authenticate with OSG Hub
        run: echo '${{ secrets.OSG_HUB_ACCESS_TOKEN }}' | docker login https://hub.opensciencegrid.org -u '${{ secrets.OSG_HUB_USERNAME }}' --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Install script dependencies
      #   run: pip3 install pyyaml

      - name: Run build.py force-build --all
        run: |
          ./build.py force-build --all \
          --push-tags 'hub.opensciencegrid.org/slate/{name}:{version}'  'hub.opensciencegrid.org/slate/{name}:{tags[]}'
        if: ${{ github.event.inputs.folders == 'ALL' }}

      - name: Run build.py force-build
        run: |
          ./build.py force-build ${{ github.event.inputs.folders }} \
          --push-tags 'hub.opensciencegrid.org/slate/{name}:{version}'  'hub.opensciencegrid.org/slate/{name}:{tags[]}'
        if: ${{ github.event.inputs.folders != 'ALL' }}
