name: PR Comment Command - Add ok-to-test label

on:
  issue_comment:
    types: [created]

jobs:
  add_label:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}

    steps:
      - run: echo "${{ toJSON(github.event) }}"

      - name: Check for ok-to-test command
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            console.log(context.event)
            return context.event.comment.body.split("\n").map(line => line.match("^[/]ok-to-test\\s*$")).some(m => m != null)
