name: PR Comment Command - Add ok-to-test label

on:
  issue_comment:
    types: [created]

jobs:
  add_label:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}

    steps:
      - run: echo "${{ toJSON(github.event) }}"
