name: PR Comment Command - Add ok-to-test label

on:
  issue_comment:
    types: [created]

jobs:
  add_label:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}

    steps:
      - name: Apply ok-to-test label if conditions are met
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            // Check if comment has "/ok-to-test" on a line by itself.
            if (!context.payload.comment.body.split("\n").map(line => line.match("^[/]ok-to-test\\s*$")).some(m => m != null)) {
              return
            }

            // Get commenter's perm level.
            const {data: {permission: permLevel}} = await github.repos.getCollaboratorPermissionLevel({
              ...context.repo,
              username: context.actor
            });
            console.log("Got perm level: " + permLevel)

            // Commenter must have perm >= write.
            if (!(permLevel === "write" || permLevel === "admin")) {
              return
            }

            await github.issues.addLabels({
              issue_number: context.issue.number,
              ...context.repo,
              labels: ['ok-to-test']
            });
