name: PR - Push PR Images

on:
  workflow_run:
    workflows: ["PR - Lint, Build, and Save Container Images"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Authenticate with Github container registry
        run: echo '${{ secrets.GITHUB_TOKEN }}' | docker login https://ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Authenticate with OSG Hub
        run: echo '${{ secrets.OSG_HUB_ACCESS_TOKEN }}' | docker login https://hub.opensciencegrid.org -u '${{ secrets.OSG_HUB_USERNAME }}' --password-stdin

      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });

            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];

            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });

            var fs = require('fs');
            fs.writeFileSync('${{ github.workspace }}/pr.zip', Buffer.from(download.data));

      - run: |
          mkdir -p images
          unzip pr.zip -d images

      - name: Push images
        id: push-tags
        shell: bash
        run: |
          set -x
          tags=""
          delim=""

          for tb in images/*; do
            if [[ "$tb" == "images/NR" ]]; then
              continue
            fi

            tags+="$delim"
            delim=" "
            tags+=$(docker load -i "$tb" | sed 's/Loaded image: //' | tr '\n' ' ')
          done

          echo "$tags" | xargs docker push || exit 1
          echo "::set-output name=TAGS::${tags}"

      - run: echo "$EVENT_CONTEXT"
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event.workflow_run) }}

      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var issue_number = Number(fs.readFileSync('images/NR'));

            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: '*This pull request has been successfully built!!*\n\nThe built images have been pushed to:\n${{ steps.push-tags.outputs.TAGS}}\n\nPlease note, these images are pushed solely for testing purposes. When this PR is closed/merged, these tags will be deleted, so **do not use these tags in production**. These images may still have lint/vuln warnings on which we did not fail on. See the full build report **[here](${{ github.event.repository.html_url }}/runs/${{ github.event.workflow_run.id }}?check_suite_focus=true#step:8:0)**.'
            });
