# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
name: PR - Lint, Build, and Save Container Images

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'labeled', 'unlocked']

jobs:
  main:
    runs-on: ubuntu-latest
    # Only run if we just labeled this PR with 'ok-to-test' or some update operation
    # occured and the PR has the label 'ok-to-test'.
    if: ${{ ( github.event.action == 'labeled' && github.event.label.name == 'ok-to-test' ) || ( github.event.action != 'labeled' && contains( github.event.pull_request.labels.*.name, 'ok-to-test' ) ) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch commit history until ${{ github.event.pull_request.base.sha }}
        run: |
          i=1
          until git show ${{ github.event.pull_request.base.sha }} &> /dev/null
          do
            if [[ $i -gt 100 ]]; then
              break
            fi

            i=$((i+5))
            git fetch --depth=$i
          done

      - name: Install hadolint
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          curl -L https://github.com/hadolint/hadolint/releases/download/v2.3.0/hadolint-Linux-x86_64 --output $GITHUB_WORKSPACE/bin/hadolint
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          chmod +x $GITHUB_WORKSPACE/bin/hadolint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Install script dependencies
      #   run: pip3 install pyyaml

      - name: Run build.py
        run: |
          ./build.py pipeline ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} \
          --save-images-to '_save/images.tar' \
          --check-existence 'ghcr.io/slateci/{name}:{version}' 'hub.opensciencegrid.org/slate/{name}:{version}' \
          --cache-from 'ghcr.io/slateci/{name}:latest' 'ghcr.io/slateci/{name}:${{ github.event.pull_request.head.ref }}' \
          --save-tags 'ghcr.io/slateci/{name}:${{ github.event.pull_request.head.ref }}'

      - name: Save PR Number
        run: |
          echo ${{ github.event.number }} > ./_save/NR

      - name: Save image artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: _save
          retention-days: 1
