name: PR - Lint, Build, and Push Container Images

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch commit history until ${{ github.event.pull_request.base.sha }}
        run: |
          i=1
          until git show ${{ github.event.pull_request.base.sha }} &> /dev/null
          do
            if [[ $i -gt 100 ]]; then
              break
            fi

            i=$((i+5))
            git fetch --depth=$i
          done

      - name: Authenticate with Github container registry
        run: echo '${{ secrets.GITHUB_TOKEN }}' | docker login https://ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Authenticate with OSG Hub
        run: echo '${{ secrets.OSG_HUB_ACCESS_TOKEN }}' | docker login https://hub.opensciencegrid.org -u '${{ secrets.OSG_HUB_USERNAME }}' --password-stdin

      - name: Install hadolint
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          curl -L https://github.com/hadolint/hadolint/releases/download/v2.3.0/hadolint-Linux-x86_64 --output $GITHUB_WORKSPACE/bin/hadolint
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          chmod +x $GITHUB_WORKSPACE/bin/hadolint

      - name: Install Docker scan plugin
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt update
          sudo apt install docker-scan-plugin -y

      # TODO: change to SLATE robot acct instead of Emerson's personal acct
      - name: Authenticate with Synk
        run: docker scan --login --token '${{ secrets.SYNK_TOKEN }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Install script dependencies
      #   run: pip3 install pyyaml

      - name: Run build.py on branch ${{ github.event.pull_request.head.ref }}
        run: ./build.py pipeline ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --ignore-version-check --branch '${{ github.event.pull_request.head.ref }}'
